### ISSUE TITLE
Connection error with .py but not with .exe

### ISSUE THREAD

**Issue by LSadarnac** [stlehmann/pyads#366]
Hello,
We are trying to connect a Windows PC to our Beckhoff PLC using pyads. We created routes on both sides. When we test the connection using TcAdsTest from the Twincat folder, everything works fine. But when calling pyads.open(), we get an error message : "Failed to open port  on AMS router". 
We also converted our python script to an executable file. When we launch the .exe, the connection is successfull. It seems that only the .py leads to an error.
Could you provide us with some help on this issue ?
Thank you.

**Comment by chrisbeardy** [comment]
Hello, thank you for your question, can I please ask that in order to assist with issue management, please keep the issue tracker reserved for bugs and feature requests. For any questions, particularly around usage, route creation and ads error messages when reading or writing variables, please use [Stack Overflow](https://stackoverflow.com/) tagging the question with twincat-ads and state you are using the pyads library, Can you also please post a minimal reproducible code example showing the issues.
